---
title: Use backdrops to create pages or levels
hero_image: images/banner.png
description: Er zijn veel manieren om de achtergrond in Scratch te veranderen om naar de volgende pagina of het volgende niveau te gaan
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Use backdrops to create pages or levels
