title: Change backdrops to create pages or levels
hero_image: images/banner.png
description: There are lots of ways to change backdrop in Scratch to switch to the next page or next level
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Change backdrops to create pages or levels
