---
title: Defnyddio cefnlenni i greu tudalennau neu lefelau
hero_image: images/banner.png
description: Mae yna lawer o ffyrdd i newid cefnlen yn Scratch er mwyn newid i'r dudalen nesaf neu'r lefel nesaf
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Defnyddio cefnlenni i greu tudalennau neu lefelau
