---
title: Mude cenários para criar páginas ou níveis
hero_image: images/banner.png
description: Existem várias maneiras de mudar o cenário no Scratch para passar para a próxima página ou próximo nível
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Use cenários para criar páginas ou níveis
