---
title: Usar fondos para crear páginas o niveles
hero_image: images/banner.png
description: Hay muchas formas de cambiar el fondo en Scratch para pasar a la siguiente página o al siguiente nivel
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Usar fondos para crear páginas o niveles
