---
title: Używaj teł do tworzenia stron lub poziomów
hero_image: images/banner.png
description: Istnieje wiele sposobów na zmianę tła w Scratchu, aby przejść do następnej strony lub następnego poziomu
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Używaj teł do tworzenia stron lub poziomów
