---
title: Använd bakgrunder för att skapa sidor eller nivåer
hero_image: images/banner.png
description: Det finns många sätt att ändra bakgrund i Scratch för att byta till nästa sida eller nästa nivå
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Använd bakgrunder för att skapa sidor eller nivåer
