---
title: Changer les arrière-plans pour créer des pages ou des niveaux
hero_image: images/banner.png
description: Il existe de nombreuses façons de changer l'arrière-plan dans Scratch pour passer à la page suivante ou au niveau suivant.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Changer les arrière-plans pour créer des pages ou des niveaux
