---
title: Utilizza gli sfondi per creare pagine o livelli
hero_image: images/banner.png
description: Esistono molti modi per cambiare lo sfondo in Scratch per passare alla pagina successiva o al livello successivo
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Utilizza gli sfondi per creare pagine o livelli
